[build-system]
requires = ["poetry-core", "setuptools"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "readmeai"
version = "0.4.0990"
description = "🚀 Generate beautiful README.md files from the terminal using GPT LLM APIs 💫"
authors = ["Eli <0x.eli.64s@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/eli64s/readme-ai"
documentation = "https://github.com/eli64s/readme-ai/blob/main/README.md"
keywords = [
  "python",
  "markdown",
  "readme",
  "ai",
  "generator",
  "devtools",
  "documentation",
  "documentation-generator",
  "readme-md",
  "readme-generator",
  "openai-api",
  "automated-readme",
  "auto-readme",
  "readme-md-generator",
  "shieldsio-badges",
  "gpt-4",
  "llm",
  "chatgpt",
  "gpt-readme"
]
include = ["readmeai", "readmeai.*"]

[tool.poetry.scripts]
readmeai = "readmeai.cli.commands:commands"

[tool.poetry.dependencies]
python = "^3.8.1,<4.0.0"
aiohttp = "^3.8.5"
cachetools = "^5.3.1"
click = "^8.1.7"
colorlog = "^6.7.0"
gitpython = "^3.1.31"
httpx = "^0.24.1"
h2 = "^4.1.0"
openai = "^0.27.8"
pyyaml = "^6.0"
responses = "^0.23.1"
tabulate = "^0.9.0"
tenacity = "^8.2.2"
tiktoken = "^0.4.0"
toml = "^0.10.2"
pydantic = ">=1.10.9,<2.0.0"
setuptools = "^69.0.3"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-randomly = "*"
pytest-sugar = "*"
pytest-xdist = "*"

[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^0.23.2"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
      .eggs
    | .git
    | .hg
    | .mypy_cache
    | .tox
    | venv
    | _build
    | buck-out
    | build
    | dist
    | notebooks
  )/
'''
virtual_env = "poetry"

[tool.flake8]
max-line-length = 79
extend-ignore = ["E203", "W503"]
exclude = ".venv,.git,.nox,docs,venv,bin,lib,deps,build,tests,examples,notebooks"

[tool.isort]
line_length = 79
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_first_party = "readmeai"
known_third_party = [
    "pytest",
    "responses",
]
sections = 'FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
no_lines_before = 'LOCALFOLDER'

[tool.coverage.run]
# branch = true
source = ["readmeai", "tests"]
omit = ["tests/*", "*__init__.py", "*/__init__.py", "noxfile.py", "setup.py"]

[tool.coverage.report]
fail_under = 70
show_missing = true

[tool.coverage.xml]
output = "coverage.xml"
